### ISSUE TITLE
Extend MinkContext instead of MinkRawContext

### ISSUE THREAD

**Issue by leevigraham** [cevou/BehatScreenshotCompareExtension#1]
Any reason why RawScreenshotCompareContext doesn't extend MinkContext? That way you get a lot more built in base step definitions?

**Comment by cevou** [comment]
There is no specifiy reason. The functionality of `MinkContext` was not needed for my developments. Maybe the screenshot funtionality should also be provided as trait, so it can be included in any context. You're welcome to contribute.
